### ISSUE TITLE
Change UIWebView to WKWebView

### ISSUE THREAD

**Issue by jstuth** [j0j00/flutter_user_agent#1]
Hey guys,
Apple changed its API deprecation information. UIWebView is now deprecated and WKWebView should now be used in order to upload an app to the AppStore.

Original App Store Connect message after uploading the App:
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information. 

I've tracked it down to this library. Are you already working on that issue?

**Comment by jstuth** [comment]
i've added a pr that will fix this #2

**Comment by rodruiz** [comment]
@Triipaxx, could you bump up to **1.0.2**?
Thanks.

**Comment by jstuth** [comment]
Unfortunately I'm not the owner of this project.
But you could check out my fork until it's part of the official project.

Add this to your yaml:
flutter_user_agent:
   git: https://github.com/Triipaxx/flutter_user_agent

Try it out and let me know if there is an issue.

**Comment by j0j00** [comment]
Thanks @Triipaxx, merged and published.

**Comment by rodruiz** [comment]
@j0j00 and @Triipaxx,
still getting the email because of [this](https://github.com/j0j00/flutter_user_agent/blob/master/ios/Classes/FlutterUserAgentPlugin.m#L164-L167) 
do we have to remove it from the else too?

I think this plugin should iOS 8 and later only and remove the code inside the else.

Thanks

**Comment by jstuth** [comment]
It could be the issue. 
What was your target iOS version?
