### ISSUE TITLE
The documentation is not clear on how to generate my own userAgent String

### ISSUE THREAD

**Issue by jucaesmanhoto** [j0j00/flutter_user_agent#10]
I am trying to find out how to implement my own userAgent, but without success for now.
I can help with the documentation if someone could teach me how to implement it.

Anyway... congratulation for your hard work. :)

**Comment by j0j00** [comment]
The example dart file should explain everything you need to know.

Just call `FlutterUserAgent.getProperty("yourPropertyName")` and use the return value to build your user agent.
