### ISSUE TITLE
FlutterUserAgentPlugin.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by davidmednikov** [j0j00/flutter_user_agent#12]
When building, I get the following warning:

`Note: C:\Users\username\Dev\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_user_agent-1.2.2\android\src\main\java\io\jojodev\flutter\flutteruseragent\FlutterUserAgentPlugin.java uses or overrides a deprecated API.`

`Note: Recompile with -Xlint:deprecation for details.`

It still works on Android, but not sure if it will forever,

**Comment by miguelpruivo** [comment]
This is not actually an "issue". t's just using deprecated API (just like a lot of other plugins).

Please fill an issue if for some reason it stops working, until there, I wouldn't worry much about it. :)

Thanks.
