### ISSUE TITLE
No podspec found for `flutter_user_agentx

### ISSUE THREAD

**Issue by andersonmendesdev** [j0j00/flutter_user_agent#22]
I was using `flutter_user_agent: 1.2.2`, but I upgrade my `flutter sdk` to `2.0.3` and saw that you were also upgrading to nullsafety `flutter_user_agentx: ^1.2.4`. I changed the lib but I get the following error in the `pod install`.

error: ```[!] No podspec found for flutter_user_agentx in .symlinks/plugins/flutter_user_agentx/ios```;

The symbolic link is inside the .sysmlink, but for some reason it does not find the .podspec. I performed the following procedures and was not successful in installing the pods.

`rm -rf ~/Library/Caches/CocoaPods`
`rm -rf ~/Library/Developer/Xcode/DerivedData/*`
`pod deintegrate `
`pod install`

`flutter doctor -v`

```
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale pt-BR)
    • Flutter version 2.0.3 at /Users/andersonmendes/development/flutter
    • Framework revision 4d7946a68d (3 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/andersonmendes/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0
```

**Comment by SlayerOrnstein** [comment]
So renaming `flutter_user_agent.podspec` to  `flutter_user_agentx.podspec` and inside podspec change name from `flutter_user_agent` to `flutter_user_agentx` solves the issue.

**Comment by mleonhard** [comment]
`flutter_user_agentx` is broken on iOS.  Use https://pub.dev/packages/fk_user_agent instead.

**Comment by j0j00** [comment]
The `flutter_user_agentx` package is an unofficial release made by someone else and incorrectly pointing to this repo.

Hopefully the null safety stuff gets resolved soon and a release made, if not, the other forks can be used for now
