### ISSUE TITLE
Error: resource android:attr/fontVariationSettings not found.

### ISSUE THREAD

**Issue by andrewpmoore** [j0j00/flutter_user_agent#6]
I've found since moving to v1.12.13+hotfix.5 I've not been able to get flutter_user_agent to build in release mode (works fine for debug mode)

From what I can tell, editing the compileSdkVersion from 27 to 28 seems to fix this

**Comment by virskor** [comment]
me too ,but my minsdk  version is s 28

**Comment by andrewpmoore** [comment]
It's not the compile version of your project, it's the one in the extension that needs amending (my project was also already on 28).

You can temporarily hack it to 28 in the flutter packages cache to get things to compile until the update comes through

**Comment by virskor** [comment]
Execution failed for task ':flutter_user_agent:verifyReleaseResources'. 
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/virs/v4.app.flutter/huaren/build/flutter_user_agent/intermediates/res/merged/release/values/values.xml:236: error: resource android:attr/fontVariationSettings not found.
  /Users/virs/v4.app.flutter/huaren/build/flutter_user_agent/intermediates/res/merged/release/values/values.xml:237: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

**Comment by virskor** [comment]
@andrewpmoore i just clone and modify it.  it worked for releasing.😃 😁

**Comment by PieterAelse** [comment]
@j0j00 could you bump the `compileSdkVersion` to 28 and create a new release?

**Comment by EliuTimana** [comment]
it seems to work when I build an appBundle, but fails on apk.

**Comment by j0j00** [comment]
Apologies for the delay.

@PieterAelse it should be addressed now in [version 1.2.2](https://pub.dev/packages/flutter_user_agent#122)
